version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    environment:
      - DOCKER_REDIRECT_URL=http://localhost:3000
      - DOCKER_RewriteCond_URL=http://localhost/
    volumes:
      - ./server:/var/www
      - ./server/apache-config:/etc/apache2/sites-available
      - ./server/apache-config/php.ini:/usr/local/etc/php/php.ini
      - ./server/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    networks:
      - default

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/var/www/client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - default

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - default

networks:
  default:
    driver: bridge
