version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default
  server:
    build: ./server
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www
    depends_on:
      - db
    networks:
      - default
    command: >
      sh -c "chmod -R 775 /var/www/storage &&
             chown -R www-data:www-data /var/www/storage &&
             apache2-foreground"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./client:/var/www/client
    depends_on:
      - server
    command: sh -c "npm install && npm run build && npm start"
    networks:
      - default

networks:
  default:
    driver: bridge
