version: '3.8'

services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile 
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: test
            TZ: 'Asia/Tokyo'
        volumes: 
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        networks:
            - default
    server:
        build: ./server
        ports:
            - "8080:80"
        volumes:
            - ./server:/var/www
        depends_on:
            - db
        networks:
            - default
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/var/www/client
        ports:
            - "3000:3000"
        depends_on: 
            - server
        command: sh -c "npm install && npm run dev"
        networks:
            - default
    mail:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025" 
        networks:
            - default

networks:
  default:
    driver: bridge